baseURL = 'https://cclljj.github.io/'
languageCode = 'en-us'
title = 'Ling-Jyh Chen'
theme = "hugo-resume"


[params]
address = "128, Sec. 2, Academia Road, Taipei 11529, Taiwan"
email = "cclljj@iis.sinica.edu.tw"
favicon = "/favicon.ico"
firstName = "Ling-Jyh"
lastName = "Chen"
phone = "+886-2-27883799#1702"
profileImage = "image/cclljj.png"
showVideo = true
showQr = false

[params.google]

[params.google.analytics]
trackerID = "G-614VHLKXM7"

[[params.handles]]
link = "https://www.linkedin.com/in/cclljj/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/cclljj/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
